name: roboshop

services:
  mongodb:
    image: mongodb:v1
    build: ./mongodb
    container_name: mongodb
    volumes:
      - mongodb:/data/db

  mysql:
    image: mysql:v1
    build: ./mysql
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  catalogue:
    image: catalogue:v1
    build: ./catalogue
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    image: user:v1
    build: ./user
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    image: cart:v1
    build: ./cart
    container_name: cart
    depends_on:
      - redis
      - catalogue

  shipping:
    image: shipping:v1
    build: ./shipping
    container_name: shipping
    depends_on:
      - mysql
      - cart

  payment:
    image: payment:v1
    build: ./payment
    container_name: payment
    depends_on:
      - rabbitmq
      - cart
      - user

  frontend:
    image: frontend:v1
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment


networks:
  default: 
    name: roboshop

volumes:
  mongodb:
    name: mongodb
  mysql:
    name: mysql
  redis:
    name: redis
  rabbitmq:
    name: rabbitmq


  
    